<!--[if (lt IE 9) & (!IEMobile)]>
<script type="text/javascript" src="theme/js/lib/html5.js"></script>
<![endif]-->
<script type="text/javascript" src="common/js/lib/jquery.min.js"></script>
<script type="text/javascript" src="theme/js/lib/device.min.js"></script>
<!--<script type="text/javascript" src="theme/js/lib/bootstrap-modal.min.js"></script>-->
<script type="text/javascript" src="theme/js/js.js"></script>